import type { ModeName } from './musicMath';

/**
 * One piece of music per cave.
 *
 * Everything that gives a cave its own tune lives here as data: the mode it
 * sits in, its chord progression, the melodic cell the lead develops, the
 * groove under it and the timbres it is played on. `musicMath` turns this into
 * notes and `MusicDirector` turns those into sound, so a cave can be rewritten
 * musically without touching either.
 *
 * Degrees are scale degrees, not semitones: 0 is the tonic, 2 a third above
 * it, 4 a fifth, 7 the octave. That keeps every theme inside its own mode no
 * matter which one it picked.
 */
export interface CaveTheme {
  /** Cave letter, for readability. */
  readonly id: string;
  /** Title of the piece. */
  readonly name: string;
  readonly mode: ModeName;
  /** Semitones from the tier's tonic; keeps neighbouring caves from matching. */
  readonly rootOffset: number;
  /** BPM with the cave at rest. */
  readonly baseTempo: number;
  /** BPM added on top at full intensity. */
  readonly tempoSpan: number;
  /** 0..0.4 shuffle: how late the offbeat sixteenths land. */
  readonly swing: number;
  /** One chord degree per bar; the loop is this long. */
  readonly progression: readonly number[];
  /**
   * Reserved turnaround colours retained for theme-data compatibility. The
   * relaxed arrangement keeps the authored progression stable.
   */
  readonly tensionChords: readonly [number, number];
  /** The melodic cell, in degrees above the bar's chord. */
  readonly motif: readonly number[];
  /** Sixteenths of the bar the motif lands on. */
  readonly rhythm: readonly number[];
  /** Bass arpeggio, one degree per eighth note. */
  readonly bassShape: readonly number[];
  /** Reserved counter-line shape retained as part of each cave's identity. */
  readonly arpShape: readonly number[];
  /** Sixteenths of the bar the kick lands on. */
  readonly kicks: readonly number[];
  /** Sixteenths of the bar the snare lands on. */
  readonly snares: readonly number[];
  readonly leadWave: OscillatorType;
  readonly bassWave: OscillatorType;
  readonly padWave: OscillatorType;
  /**
   * How the drums are voiced. `soft` is a felt kick and a brushed snare,
   * `tight` a punchy studio kit, `hard` a gated slam with a long tail.
   */
  readonly kit: DrumKit;
  /** 0..1 weight of the struck-bell cadence accent. Crystalline caves ring. */
  readonly bellMix: number;
  /** 0..1 weight of the sine sub under the bass. Deep caves rumble. */
  readonly subMix: number;
  /** 0..1 weight of the filtered air bed. Big open caves breathe. */
  readonly airMix: number;
}

/** Drum voicings, darkening down the campaign. */
export type DrumKit = 'soft' | 'tight' | 'hard';

/**
 * Twenty themes, one per cave, ordered to darken across the campaign: open
 * dorian tunes with a swung, patient groove at the top and darker modal
 * colours toward the bottom.
 */
export const THEMES: readonly CaveTheme[] = [
  {
    id: 'A',
    name: 'Buried River',
    mode: 'dorian',
    rootOffset: 0,
    baseTempo: 86,
    tempoSpan: 14,
    swing: 0.18,
    progression: [0, 3, 5, 2],
    tensionChords: [2, 4],
    motif: [0, 1, 3, 4, 2, 0],
    rhythm: [0, 3, 6, 9, 11, 14],
    bassShape: [0, 2, 4, 6],
    arpShape: [0, 1, 3, 2],
    kicks: [0, 10],
    snares: [6, 14],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'soft',
    bellMix: 0.55,
    subMix: 0.3,
    airMix: 0.65,
  },
  {
    id: 'B',
    name: 'Rockfall',
    mode: 'aeolian',
    rootOffset: -1,
    baseTempo: 94,
    tempoSpan: 14,
    swing: 0,
    progression: [0, 4, 2, 5],
    tensionChords: [2, 5],
    motif: [0, 4, 3, 1, -1, 0],
    rhythm: [0, 2, 5, 8, 12, 15],
    bassShape: [0, 0, 4, 1],
    arpShape: [0, 4, 3, 1],
    kicks: [0, 7, 12],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'soft',
    bellMix: 0.25,
    subMix: 0.5,
    airMix: 0.35,
  },
  {
    id: 'C',
    name: 'Side Pocket',
    mode: 'dorian',
    rootOffset: 1,
    baseTempo: 88,
    tempoSpan: 12,
    swing: 0.2,
    progression: [0, 2, 4, 3],
    tensionChords: [2, 4],
    motif: [0, 3, 1, 4, 2, 0],
    rhythm: [0, 4, 7, 9, 12, 15],
    bassShape: [0, 4, 2, 6],
    arpShape: [0, 3, 1, 4],
    kicks: [0, 10],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'soft',
    bellMix: 0.5,
    subMix: 0.25,
    airMix: 0.6,
  },
  {
    id: 'D',
    name: 'Switchbacks',
    mode: 'aeolian',
    rootOffset: 0,
    baseTempo: 98,
    tempoSpan: 14,
    swing: 0.1,
    progression: [0, 5, 2, 4],
    tensionChords: [2, 5],
    motif: [0, 3, 1, 4, 2, 5, 0],
    rhythm: [0, 2, 5, 7, 9, 13, 15],
    bassShape: [0, 3, 1, 5],
    arpShape: [0, 3, 1, 4],
    kicks: [0, 6, 11],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'soft',
    bellMix: 0.2,
    subMix: 0.45,
    airMix: 0.4,
  },
  {
    id: 'E',
    name: 'Spark Lock',
    mode: 'harmonicMinor',
    rootOffset: -1,
    baseTempo: 100,
    tempoSpan: 12,
    swing: 0.08,
    progression: [0, 3, 6, 4],
    tensionChords: [3, 6],
    motif: [0, 1, 4, 2, 5, 0],
    rhythm: [0, 5, 6, 10, 11, 15],
    bassShape: [0, 4, 1, 6],
    arpShape: [0, 1, 4, 2],
    kicks: [0, 8],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'sine',
    kit: 'soft',
    bellMix: 0.65,
    subMix: 0.4,
    airMix: 0.5,
  },
  {
    id: 'F',
    name: 'Double Fuse',
    mode: 'aeolian',
    rootOffset: 0,
    baseTempo: 102,
    tempoSpan: 16,
    swing: 0.06,
    progression: [0, 4, 0, 5],
    tensionChords: [2, 5],
    motif: [0, 2, 0, 4, 3, 5, 0],
    rhythm: [0, 2, 4, 8, 10, 12, 15],
    bassShape: [0, 0, 4, 4],
    arpShape: [0, 2, 0, 4],
    kicks: [0, 6, 8, 14],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'soft',
    bellMix: 0.2,
    subMix: 0.55,
    airMix: 0.35,
  },
  {
    id: 'G',
    name: 'Rich Strike',
    mode: 'dorian',
    rootOffset: 1,
    baseTempo: 92,
    tempoSpan: 14,
    swing: 0.22,
    progression: [0, 5, 2, 4],
    tensionChords: [2, 5],
    motif: [0, 4, 2, 5, 3, 6, 0],
    rhythm: [0, 3, 5, 8, 10, 13, 15],
    bassShape: [0, 2, 5, 3],
    arpShape: [0, 4, 2, 5],
    kicks: [0, 10],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'soft',
    bellMix: 0.6,
    subMix: 0.35,
    airMix: 0.65,
  },
  {
    id: 'H',
    name: 'Seven Furnaces',
    mode: 'harmonicMinor',
    rootOffset: 0,
    baseTempo: 96,
    tempoSpan: 16,
    swing: 0.1,
    progression: [0, 4, 1, 5],
    tensionChords: [3, 5],
    motif: [0, 2, 4, 6, 5, 3, 0],
    rhythm: [0, 2, 4, 7, 10, 13, 15],
    bassShape: [0, 4, 6, 2],
    arpShape: [0, 2, 4, 6],
    kicks: [0, 8, 14],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.7,
    subMix: 0.45,
    airMix: 0.55,
  },
  {
    id: 'I',
    name: 'Relay Kilns',
    mode: 'harmonicMinor',
    rootOffset: -1,
    baseTempo: 98,
    tempoSpan: 16,
    swing: 0.08,
    progression: [0, 3, 0, 4],
    tensionChords: [3, 4],
    motif: [0, 3, 1, 0, 4, 2, 0],
    rhythm: [0, 2, 4, 7, 9, 12, 15],
    bassShape: [0, 3, 0, 5],
    arpShape: [0, 3, 1, 4],
    kicks: [0, 8],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.55,
    subMix: 0.45,
    airMix: 0.55,
  },
  {
    id: 'J',
    name: 'Seed Crystal',
    mode: 'dorian',
    rootOffset: 0,
    baseTempo: 88,
    tempoSpan: 14,
    swing: 0.24,
    progression: [0, 1, 3, 5],
    tensionChords: [3, 5],
    motif: [0, 1, 2, 4, 5, 3, 0],
    rhythm: [0, 3, 6, 8, 11, 13, 15],
    bassShape: [0, 1, 3, 5],
    arpShape: [0, 1, 2, 4],
    kicks: [0, 10],
    snares: [6, 14],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.45,
    subMix: 0.4,
    airMix: 0.75,
  },
  {
    id: 'K',
    name: 'Closing Shift',
    mode: 'phrygian',
    rootOffset: 0,
    baseTempo: 100,
    tempoSpan: 16,
    swing: 0.08,
    progression: [0, 1, 3, 4],
    tensionChords: [1, 4],
    motif: [0, 1, 3, 2, 4, 5, 0],
    rhythm: [0, 2, 5, 7, 9, 12, 15],
    bassShape: [0, 1, 3, 1],
    arpShape: [0, 1, 3, 2],
    kicks: [0, 8, 13],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.2,
    subMix: 0.55,
    airMix: 0.4,
  },
  {
    id: 'L',
    name: 'Bloom Chase',
    mode: 'hungarian',
    rootOffset: 1,
    baseTempo: 94,
    tempoSpan: 14,
    swing: 0.16,
    progression: [0, 3, 5, 2],
    tensionChords: [3, 5],
    motif: [0, 2, 5, 3, 6, 4, 0],
    rhythm: [0, 2, 4, 7, 9, 11, 15],
    bassShape: [0, 3, 5, 2],
    arpShape: [0, 2, 5, 3],
    kicks: [0, 10],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.4,
    subMix: 0.5,
    airMix: 0.7,
  },
  {
    id: 'M',
    name: 'Membrane Drop',
    mode: 'phrygian',
    rootOffset: -1,
    baseTempo: 96,
    tempoSpan: 16,
    swing: 0.12,
    progression: [0, 5, 1, 3],
    tensionChords: [1, 5],
    motif: [0, 4, 2, 1, -1, 3, 0],
    rhythm: [0, 4, 6, 8, 10, 13, 15],
    bassShape: [0, 3, 1, 4],
    arpShape: [0, 4, 2, 1],
    kicks: [0, 8],
    snares: [6, 14],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.3,
    subMix: 0.6,
    airMix: 0.75,
  },
  {
    id: 'N',
    name: 'Crossed Wires',
    mode: 'harmonicMinor',
    rootOffset: 0,
    baseTempo: 104,
    tempoSpan: 14,
    swing: 0.06,
    progression: [0, 4, 2, 6],
    tensionChords: [2, 6],
    motif: [0, 4, 1, 5, 2, 6, 0],
    rhythm: [0, 2, 5, 7, 10, 12, 15],
    bassShape: [0, 4, 1, 5],
    arpShape: [0, 4, 1, 5],
    kicks: [0, 6, 10],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.35,
    subMix: 0.55,
    airMix: 0.4,
  },
  {
    id: 'O',
    name: 'Twin Blooms',
    mode: 'aeolian',
    rootOffset: 1,
    baseTempo: 90,
    tempoSpan: 16,
    swing: 0.2,
    progression: [0, 3, 1, 5],
    tensionChords: [1, 5],
    motif: [0, 2, 4, 2, 1, 3, 5, 0],
    rhythm: [0, 2, 4, 6, 9, 11, 13, 15],
    bassShape: [0, 2, 4, 2],
    arpShape: [0, 2, 1, 3],
    kicks: [0, 10],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.4,
    subMix: 0.55,
    airMix: 0.75,
  },
  {
    id: 'P',
    name: 'Alloy and Wings',
    mode: 'hungarian',
    rootOffset: 0,
    baseTempo: 100,
    tempoSpan: 16,
    swing: 0.08,
    progression: [0, 4, 6, 3],
    tensionChords: [3, 6],
    motif: [0, 3, 6, 4, 1, 5, 2, 0],
    rhythm: [0, 2, 4, 6, 8, 10, 13, 15],
    bassShape: [0, 3, 6, 4],
    arpShape: [0, 3, 1, 5],
    kicks: [0, 8, 14],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.55,
    subMix: 0.6,
    airMix: 0.5,
  },
  {
    id: 'Q',
    name: 'Three Charges',
    mode: 'harmonicMinor',
    rootOffset: -1,
    baseTempo: 102,
    tempoSpan: 16,
    swing: 0.06,
    progression: [0, 3, 0, 5],
    tensionChords: [3, 5],
    motif: [0, 3, 0, 4, 1, 5, 0],
    rhythm: [0, 1, 4, 6, 9, 11, 15],
    bassShape: [0, 0, 3, 3],
    arpShape: [0, 3, 0, 4],
    kicks: [0, 5, 10],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.35,
    subMix: 0.6,
    airMix: 0.45,
  },
  {
    id: 'R',
    name: 'Blast Passage',
    mode: 'phrygian',
    rootOffset: 1,
    baseTempo: 106,
    tempoSpan: 14,
    swing: 0.04,
    progression: [0, 1, 4, 3],
    tensionChords: [1, 4],
    motif: [0, 1, 4, 0, 5, 2, 0],
    rhythm: [0, 2, 6, 8, 10, 14, 15],
    bassShape: [0, 1, 4, 1],
    arpShape: [0, 1, 4, 2],
    kicks: [0, 8, 14],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.2,
    subMix: 0.65,
    airMix: 0.35,
  },
  {
    id: 'S',
    name: 'Cascade Works',
    mode: 'locrian',
    rootOffset: -1,
    baseTempo: 104,
    tempoSpan: 16,
    swing: 0.08,
    progression: [0, 6, 3, 5],
    tensionChords: [3, 5],
    motif: [0, 6, 5, 3, 2, 1, 0],
    rhythm: [0, 2, 4, 6, 9, 12, 15],
    bassShape: [0, 6, 4, 2],
    arpShape: [0, 6, 5, 3],
    kicks: [0, 8],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'square',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.5,
    subMix: 0.65,
    airMix: 0.65,
  },
  {
    id: 'T',
    name: 'Foundry Run',
    mode: 'locrian',
    rootOffset: 0,
    baseTempo: 108,
    tempoSpan: 16,
    swing: 0.04,
    progression: [0, 4, 1, 5],
    tensionChords: [1, 5],
    motif: [0, 2, 5, 1, 6, 3, 4, 0],
    rhythm: [0, 2, 4, 6, 8, 10, 12, 15],
    bassShape: [0, 4, 2, 5],
    arpShape: [0, 2, 5, 1],
    kicks: [0, 6, 12],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.6,
    subMix: 0.7,
    airMix: 0.7,
  },
];

/**
 * The theme for a cave. Indices past the end of the table wrap, so a longer
 * campaign keeps playing music rather than falling over.
 */
export function themeForCave(caveIndex: number): CaveTheme {
  const index = Number.isFinite(caveIndex) ? Math.max(0, Math.floor(caveIndex)) : 0;
  return THEMES[index % THEMES.length];
}
