import type { ModeName } from './musicMath';

/**
 * One piece of music per cave.
 *
 * Everything that gives a cave its own tune lives here as data: the mode it
 * sits in, its chord progression, the melodic cell the lead develops, the
 * groove under it and the timbres it is played on. `musicMath` turns this into
 * notes and `MusicDirector` turns those into sound, so a cave can be rewritten
 * musically without touching either.
 *
 * Degrees are scale degrees, not semitones: 0 is the tonic, 2 a third above
 * it, 4 a fifth, 7 the octave. That keeps every theme inside its own mode no
 * matter which one it picked.
 */
export interface CaveTheme {
  /** Cave letter, for readability. */
  readonly id: string;
  /** Title of the piece. */
  readonly name: string;
  readonly mode: ModeName;
  /** Semitones from the tier's tonic; keeps neighbouring caves from matching. */
  readonly rootOffset: number;
  /** BPM with the cave at rest. */
  readonly baseTempo: number;
  /** BPM added on top at full intensity. */
  readonly tempoSpan: number;
  /** 0..0.4 shuffle: how late the offbeat sixteenths land. */
  readonly swing: number;
  /** One chord degree per bar; the loop is this long. */
  readonly progression: readonly number[];
  /**
   * What the final bar turns into once the cave gets serious: the first entry
   * from the "drive" phase, the second from "panic". Darker degrees here are
   * what makes the loop stop resolving.
   */
  readonly tensionChords: readonly [number, number];
  /** The melodic cell, in degrees above the bar's chord. */
  readonly motif: readonly number[];
  /** Sixteenths of the bar the motif lands on. */
  readonly rhythm: readonly number[];
  /** Bass arpeggio, one degree per eighth note. */
  readonly bassShape: readonly number[];
  /** Counter-line arpeggio, one degree per sixteenth. */
  readonly arpShape: readonly number[];
  /** Sixteenths of the bar the kick lands on. */
  readonly kicks: readonly number[];
  /** Sixteenths of the bar the snare lands on. */
  readonly snares: readonly number[];
  readonly leadWave: OscillatorType;
  readonly bassWave: OscillatorType;
  readonly padWave: OscillatorType;
  /**
   * How the drums are voiced. `soft` is a felt kick and a brushed snare,
   * `tight` a punchy studio kit, `hard` a gated slam with a long tail.
   */
  readonly kit: DrumKit;
  /** 0..1 weight of the struck-bell counter-line. Crystalline caves ring. */
  readonly bellMix: number;
  /** 0..1 weight of the sine sub under the bass. Deep caves rumble. */
  readonly subMix: number;
  /** 0..1 weight of the filtered air bed. Big open caves breathe. */
  readonly airMix: number;
}

/** Drum voicings, darkening down the campaign. */
export type DrumKit = 'soft' | 'tight' | 'hard';

/**
 * Twenty themes, one per cave, ordered to darken across the campaign: open
 * dorian tunes with a swung, patient groove at the top, airless locrian ones
 * that never resolve at the bottom.
 */
export const THEMES: readonly CaveTheme[] = [
  {
    id: 'A',
    name: 'First Descent',
    mode: 'dorian',
    rootOffset: 0,
    baseTempo: 94,
    tempoSpan: 56,
    swing: 0.16,
    progression: [0, 5, 3, 4],
    tensionChords: [1, 6],
    motif: [0, 2, 4, 2, 1],
    rhythm: [0, 4, 6, 10, 12],
    bassShape: [0, 4, 7, 4],
    arpShape: [0, 2, 4, 2],
    kicks: [0, 6],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'soft',
    bellMix: 0.85,
    subMix: 0.25,
    airMix: 0.55,
  },
  {
    id: 'B',
    name: 'Rockfall',
    mode: 'aeolian',
    rootOffset: -1,
    baseTempo: 102,
    tempoSpan: 58,
    swing: 0.08,
    progression: [0, 3, 4, 3],
    tensionChords: [1, 5],
    motif: [0, 1, 2, 4, 2, 0],
    rhythm: [0, 2, 6, 8, 12, 14],
    bassShape: [0, 0, 7, 5],
    arpShape: [0, 4, 2, 6],
    kicks: [0, 8, 11],
    snares: [4, 12],
    leadWave: 'square',
    bassWave: 'sawtooth',
    padWave: 'triangle',
    kit: 'soft',
    bellMix: 0.35,
    subMix: 0.45,
    airMix: 0.4,
  },
  {
    id: 'C',
    name: 'The Gallery',
    mode: 'dorian',
    rootOffset: 1,
    baseTempo: 90,
    tempoSpan: 54,
    swing: 0.22,
    progression: [0, 4, 5, 2],
    tensionChords: [1, 6],
    motif: [0, 3, 2, 4, 5, 4],
    rhythm: [0, 3, 6, 9, 12],
    bassShape: [0, 4, 7, 9],
    arpShape: [0, 2, 4, 6],
    kicks: [0, 6],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'square',
    padWave: 'sine',
    kit: 'soft',
    bellMix: 0.9,
    subMix: 0.3,
    airMix: 0.7,
  },
  {
    id: 'D',
    name: 'Pushing Through',
    mode: 'aeolian',
    rootOffset: 0,
    baseTempo: 106,
    tempoSpan: 60,
    swing: 0.05,
    progression: [0, 6, 5, 4],
    tensionChords: [1, 5],
    motif: [0, 2, 1, 0, 4],
    rhythm: [0, 4, 8, 10, 12],
    bassShape: [0, 7, 0, 5],
    arpShape: [0, 4, 7, 4],
    kicks: [0, 4, 10],
    snares: [4, 12],
    leadWave: 'sawtooth',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'soft',
    bellMix: 0.3,
    subMix: 0.5,
    airMix: 0.35,
  },
  {
    id: 'E',
    name: 'Firefly Warren',
    mode: 'dorian',
    rootOffset: -1,
    baseTempo: 114,
    tempoSpan: 58,
    swing: 0.14,
    progression: [0, 5, 1, 4],
    tensionChords: [1, 6],
    motif: [0, 4, 3, 2, 4, 6],
    rhythm: [0, 2, 4, 7, 10, 13],
    bassShape: [0, 2, 4, 2],
    arpShape: [0, 3, 5, 3],
    kicks: [0, 6, 12],
    snares: [4, 12],
    leadWave: 'square',
    bassWave: 'square',
    padWave: 'sine',
    kit: 'soft',
    bellMix: 0.5,
    subMix: 0.5,
    airMix: 0.45,
  },
  {
    id: 'F',
    name: 'Crush Depth',
    mode: 'aeolian',
    rootOffset: 0,
    baseTempo: 98,
    tempoSpan: 62,
    swing: 0.1,
    progression: [0, 5, 3, 6],
    tensionChords: [1, 6],
    motif: [0, -1, 2, 1, 4],
    rhythm: [0, 4, 6, 12],
    bassShape: [0, 5, 7, 5],
    arpShape: [0, 2, 4, 2],
    kicks: [0, 7, 10],
    snares: [4, 12],
    leadWave: 'triangle',
    bassWave: 'sawtooth',
    padWave: 'triangle',
    kit: 'soft',
    bellMix: 0.25,
    subMix: 0.6,
    airMix: 0.3,
  },
  {
    id: 'G',
    name: 'Butterfly Vault',
    mode: 'dorian',
    rootOffset: 1,
    baseTempo: 94,
    tempoSpan: 56,
    swing: 0.2,
    progression: [0, 4, 2, 5],
    tensionChords: [1, 3],
    motif: [0, 2, 5, 4, 2, 1],
    rhythm: [0, 3, 6, 8, 11, 14],
    bassShape: [0, 4, 7, 4],
    arpShape: [0, 4, 2, 6],
    kicks: [0, 6],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.75,
    subMix: 0.45,
    airMix: 0.6,
  },
  {
    id: 'H',
    name: 'Magic Seam',
    mode: 'harmonicMinor',
    rootOffset: 0,
    baseTempo: 102,
    tempoSpan: 60,
    swing: 0.12,
    progression: [0, 3, 4, 4],
    tensionChords: [1, 6],
    motif: [0, 4, 6, 4, 2],
    rhythm: [0, 2, 6, 10, 14],
    bassShape: [0, 4, 7, 4],
    arpShape: [0, 2, 4, 6],
    kicks: [0, 8],
    snares: [4, 12],
    leadWave: 'square',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.95,
    subMix: 0.4,
    airMix: 0.65,
  },
  {
    id: 'I',
    name: 'The Sieve',
    mode: 'aeolian',
    rootOffset: -1,
    baseTempo: 110,
    tempoSpan: 62,
    swing: 0.06,
    progression: [0, 6, 4, 3],
    tensionChords: [1, 5],
    motif: [0, 1, 0, 2, -1],
    rhythm: [0, 2, 4, 8, 10, 12],
    bassShape: [0, 0, 5, 7],
    arpShape: [0, 3, 5, 3],
    kicks: [0, 4, 8, 12],
    snares: [6, 14],
    leadWave: 'sawtooth',
    bassWave: 'square',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.8,
    subMix: 0.5,
    airMix: 0.5,
  },
  {
    id: 'J',
    name: 'Green Tide',
    mode: 'dorian',
    rootOffset: 0,
    baseTempo: 90,
    tempoSpan: 58,
    swing: 0.24,
    progression: [0, 2, 5, 4],
    tensionChords: [1, 6],
    motif: [0, 2, 4, 5, 4, 2],
    rhythm: [0, 4, 7, 10, 12],
    bassShape: [0, 4, 2, 4],
    arpShape: [0, 2, 4, 2],
    kicks: [0, 6],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.45,
    subMix: 0.55,
    airMix: 0.7,
  },
  {
    id: 'K',
    name: 'Expanding Ruin',
    mode: 'phrygian',
    rootOffset: 0,
    baseTempo: 104,
    tempoSpan: 62,
    swing: 0.1,
    progression: [0, 1, 5, 4],
    tensionChords: [1, 6],
    motif: [0, 1, 4, 3, 1],
    rhythm: [0, 3, 6, 10, 13],
    bassShape: [0, 5, 7, 5],
    arpShape: [0, 1, 4, 1],
    kicks: [0, 6, 10],
    snares: [4, 12],
    leadWave: 'square',
    bassWave: 'sawtooth',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.35,
    subMix: 0.6,
    airMix: 0.4,
  },
  {
    id: 'L',
    name: 'Growth Chamber',
    mode: 'hungarian',
    rootOffset: 1,
    baseTempo: 96,
    tempoSpan: 58,
    swing: 0.18,
    progression: [0, 4, 3, 6],
    tensionChords: [1, 3],
    motif: [0, 3, 2, 5, 3],
    rhythm: [0, 2, 5, 8, 12],
    bassShape: [0, 3, 7, 3],
    arpShape: [0, 3, 5, 3],
    kicks: [0, 7],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'square',
    padWave: 'sine',
    kit: 'tight',
    bellMix: 0.5,
    subMix: 0.6,
    airMix: 0.6,
  },
  {
    id: 'M',
    name: 'Slime Pits',
    mode: 'phrygian',
    rootOffset: -1,
    baseTempo: 108,
    tempoSpan: 60,
    swing: 0.08,
    progression: [0, 1, 3, 1],
    tensionChords: [1, 6],
    motif: [0, -1, 1, 3, 1],
    rhythm: [0, 4, 6, 8, 12, 14],
    bassShape: [0, 1, 5, 1],
    arpShape: [0, 2, 3, 2],
    kicks: [0, 4, 8, 12],
    snares: [6, 14],
    leadWave: 'sawtooth',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.4,
    subMix: 0.65,
    airMix: 0.75,
  },
  {
    id: 'N',
    name: 'Double Trouble',
    mode: 'harmonicMinor',
    rootOffset: 0,
    baseTempo: 116,
    tempoSpan: 62,
    swing: 0.05,
    progression: [0, 4, 0, 5],
    tensionChords: [1, 6],
    motif: [0, 2, 4, 2, 6, 4],
    rhythm: [0, 2, 4, 6, 10, 12],
    bassShape: [0, 7, 4, 7],
    arpShape: [0, 4, 2, 6],
    kicks: [0, 3, 6, 10],
    snares: [4, 12],
    leadWave: 'square',
    bassWave: 'sawtooth',
    padWave: 'triangle',
    kit: 'tight',
    bellMix: 0.55,
    subMix: 0.65,
    airMix: 0.45,
  },
  {
    id: 'O',
    name: 'Amoeba Bloom',
    mode: 'phrygian',
    rootOffset: 1,
    baseTempo: 92,
    tempoSpan: 64,
    swing: 0.22,
    progression: [0, 1, 6, 5],
    tensionChords: [1, 4],
    motif: [0, 1, 3, 4, 3, 1],
    rhythm: [0, 3, 6, 9, 12, 15],
    bassShape: [0, 3, 5, 3],
    arpShape: [0, 1, 3, 5],
    kicks: [0, 6],
    snares: [4, 12],
    leadWave: 'sine',
    bassWave: 'triangle',
    padWave: 'sine',
    kit: 'hard',
    bellMix: 0.45,
    subMix: 0.7,
    airMix: 0.7,
  },
  {
    id: 'P',
    name: 'The Crucible',
    mode: 'locrian',
    rootOffset: 0,
    baseTempo: 110,
    tempoSpan: 64,
    swing: 0.06,
    progression: [0, 4, 3, 1],
    tensionChords: [1, 6],
    motif: [0, 2, 3, 2, 5],
    rhythm: [0, 2, 6, 8, 12],
    bassShape: [0, 4, 6, 4],
    arpShape: [0, 2, 4, 6],
    kicks: [0, 6, 10],
    snares: [4, 12],
    leadWave: 'sawtooth',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'hard',
    bellMix: 0.85,
    subMix: 0.7,
    airMix: 0.5,
  },
  {
    id: 'Q',
    name: 'Nest of Wings',
    mode: 'hungarian',
    rootOffset: -1,
    baseTempo: 114,
    tempoSpan: 62,
    swing: 0.12,
    progression: [0, 3, 4, 6],
    tensionChords: [1, 5],
    motif: [0, 4, 3, 6, 4, 2],
    rhythm: [0, 3, 5, 8, 11, 14],
    bassShape: [0, 3, 7, 3],
    arpShape: [0, 3, 4, 6],
    kicks: [0, 4, 8, 11],
    snares: [4, 12],
    leadWave: 'square',
    bassWave: 'sawtooth',
    padWave: 'sine',
    kit: 'hard',
    bellMix: 0.6,
    subMix: 0.75,
    airMix: 0.55,
  },
  {
    id: 'R',
    name: 'Choke Point',
    mode: 'phrygian',
    rootOffset: 1,
    baseTempo: 120,
    tempoSpan: 60,
    swing: 0.04,
    progression: [0, 1, 0, 4],
    tensionChords: [1, 6],
    motif: [0, 1, 0, -1, 1],
    rhythm: [0, 2, 4, 8, 10, 12],
    bassShape: [0, 0, 1, 0],
    arpShape: [0, 1, 2, 1],
    kicks: [0, 2, 6, 8, 12],
    snares: [4, 12],
    leadWave: 'square',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'hard',
    bellMix: 0.3,
    subMix: 0.8,
    airMix: 0.35,
  },
  {
    id: 'S',
    name: 'Cascade',
    mode: 'locrian',
    rootOffset: -1,
    baseTempo: 118,
    tempoSpan: 64,
    swing: 0.1,
    progression: [0, 6, 4, 2],
    tensionChords: [1, 5],
    motif: [6, 4, 2, 0, -1, 1],
    rhythm: [0, 2, 4, 7, 10, 13],
    bassShape: [0, 6, 4, 2],
    arpShape: [6, 4, 2, 0],
    kicks: [0, 6, 12],
    snares: [4, 12],
    leadWave: 'sawtooth',
    bassWave: 'sawtooth',
    padWave: 'sine',
    kit: 'hard',
    bellMix: 0.7,
    subMix: 0.8,
    airMix: 0.6,
  },
  {
    id: 'T',
    name: 'One Way Out',
    mode: 'locrian',
    rootOffset: 0,
    baseTempo: 124,
    tempoSpan: 64,
    swing: 0,
    progression: [0, 1, 4, 6],
    tensionChords: [1, 6],
    motif: [0, 4, 6, 4, 1, 0],
    rhythm: [0, 2, 5, 8, 10, 14],
    bassShape: [0, 4, 6, 7],
    arpShape: [0, 4, 6, 4],
    kicks: [0, 4, 8, 12],
    snares: [4, 12],
    leadWave: 'sawtooth',
    bassWave: 'square',
    padWave: 'triangle',
    kit: 'hard',
    bellMix: 0.9,
    subMix: 0.9,
    airMix: 0.8,
  },
];

/**
 * The theme for a cave. Indices past the end of the table wrap, so a longer
 * campaign keeps playing music rather than falling over.
 */
export function themeForCave(caveIndex: number): CaveTheme {
  const index = Number.isFinite(caveIndex) ? Math.max(0, Math.floor(caveIndex)) : 0;
  return THEMES[index % THEMES.length];
}
