import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** C — The Gallery. Sealed vaults, each with one way in. */
export const caveC: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveC',
  letter: 'C',
  name: 'The Gallery',
  paletteId: 'rime',
  hint: 'Every vault has a door. Find it before the clock does.',
  diamondsRequired: 20,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 140,
  tickHz: 7.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......r........r........r........r....W',
    'W...wwwwww...wwwwww...wwwwww...wwwwww..W',
    'W...w....w...w....w...w....w...w....w..W',
    'W...w.dd.w...w.dd.w...w.dd.w...w.dd.w..W',
    'W...w.dd.w...w.dd.w...w.dd.w...w.dd.w..W',
    'W...ww.www...ww.www...ww.www...ww.www..W',
    'W......................................W',
    'W.r...r...r...r...r...r...r...r...r....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWW....WWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W...wwwwww...wwwwww...wwwwww...wwwwww..W',
    'W...w....w...w....w...w....w...w....w..W',
    'W...w.dd.w...w.dd.w...w.dd.w...w.dd.w..W',
    'W...w.dd.w...w.dd.w...w.dd.w...w.dd.w..W',
    'W...www.ww...www.ww...www.ww...www.ww..W',
    'W......................................W',
    'W....r....r....r....r....r....r....r...W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
