import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** N — Crossed Wires. Empty blasts open vaults; rich blasts pay the quota. */
export const caveN: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveN',
  letter: 'N',
  name: 'Crossed Wires',
  paletteId: 'sulphur',
  hint: 'Fireflies open doors. Butterflies leave treasure. Use both.',
  objective: 'Use empty and diamond-producing blasts to clear the crossed vaults.',
  mechanics: ['gravity', 'fireflies', 'butterflies'],
  difficulty: 4,
  diamondsRequired: 26,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 48,
  tickHz: 8.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...................d..................W',
    'W.........rwwwwwww...........r.........W',
    'W..........w.d.d.w............w........W',
    'W........wfw.d.d.w..........wbw........W',
    'W........www.d.d.w..........www........W',
    'W..........wwwwwww.....................W',
    'W......................................W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWW',
    'W......................................W',
    'W......................................W',
    'W.........r..................rwwwwwww..W',
    'W..........w..................w.d.d.w..W',
    'W........wBw................wFw.d.d.w..W',
    'W........www................www.d.d.w..W',
    'W.............................wwwwwww..W',
    'W......................................W',
    'W...................d..................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
