import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** D — Pushing Through. Rock plugs, and cellars you have to shove your way into. */
export const caveD: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveD',
  letter: 'D',
  name: 'Pushing Through',
  paletteId: 'ember',
  hint: 'Walk into a boulder with space behind it and it gives way.',
  diamondsRequired: 20,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 135,
  tickHz: 7.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d....d....d....d....d....d....d....W',
    'W......r.......r.......r.......r.......W',
    'W...d....d....d....d....d....d....d....W',
    'W......................................W',
    'W..WWWWWWWWW..WWWWWWWWWWWW..WWWWWWWWW..W',
    'W......................................W',
    'W..rr....rr....rr....rr....rr....rr....W',
    'W..dd....dd....dd....dd....dd....dd....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW....W',
    'W......................................W',
    'W.....w    w......w    w......w    w...W',
    'W.....w rr w......w rr w......w rr w...W',
    'W.....w dd w......w dd w......w dd w...W',
    'W.....wwww.w......wwww.w......wwww.w...W',
    'W......................................W',
    'W..d....d....d....d....d....d....d.....W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
