import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** L — Growth Chamber. A sealed colony hardening into a stash you must break into. */
export const caveL: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveL',
  letter: 'L',
  name: 'Growth Chamber',
  paletteId: 'amethyst',
  hint: 'Two things in here are growing. Neither is on your side.',
  diamondsRequired: 24,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 150,
  tickHz: 8,
  amoebaGrowthChance: 0.2,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W......wwwwwwww........................W',
    'W......w      w........................W',
    'W......w  aa  r........................W',
    'W......w      w........................W',
    'W......wwwwwwww........................W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W.........................H............W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
