import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** I — The Sieve. Three seams, one short charge between them. */
export const caveI: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveI',
  letter: 'I',
  name: 'The Sieve',
  paletteId: 'verdant',
  hint: 'Two seams, one charge. Spend it well.',
  diamondsRequired: 24,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 135,
  tickHz: 8,
  magicWallTicks: 150,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d.......d.......d.......d.......d..W',
    'W......................................W',
    'W..rrrrrrrrrrr..........rrrrrrrrrrr....W',
    'W......................................W',
    'W..MMMMMMMMMMM..........MMMMMMMMMMM....W',
    'W..           ..........           ....W',
    'W..           ..........           ....W',
    'W..WWWWWWWWWWW..........WWWWWWWWWWW....W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W.....rrrrrrrrrrrrrrrrrrrrrrrrrrrr.....W',
    'W......................................W',
    'W.....MMMMMMMMMMMMMMMMMMMMMMMMMMMM.....W',
    'W.....                            .....W',
    'W.....                            .....W',
    'W.....WWWWWWWWWWWWWWWWWWWWWWWWWWWW.....W',
    'W...d...d...d...d...d...d...d........E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
