import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** L — Growth Chamber. Two things in here are growing. Neither is on your side. */
export const caveL: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveL',
  letter: 'L',
  name: 'Growth Chamber',
  paletteId: 'amethyst',
  hint: 'Two things in here are growing. Neither is on your side.',
  diamondsRequired: 20,
  diamondValue: 14,
  extraDiamondValue: 35,
  timeLimit: 155,
  tickHz: 8,
  amoebaSlowGrowthTicks: 90,
  amoebaGrowthChance: 0.2,
  amoebaMaxSize: 110,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.r............W.......................W',
    'W.d..........d.Wr...r........d....d....W',
    'W...          .W........ddd...r...r....W',
    'W...    V     .W.d.......rd............W',
    'W...          .W.wwwwwwwwwwwwwwwwwwww..W',
    'W...          .W.w                  w..W',
    'W...          .W.w                  w..W',
    'W...          .W.w                  ...W',
    'W...          .W.w                  w..W',
    'W.d.          .W.w        a         w..W',
    'W...          .W.w                  w.dW',
    'W...          .W.w                  w.dW',
    'W...          .W.w                  w..W',
    'W...          .Wdw                  w..W',
    'W...          .W..                  w..W',
    'W...          .W.wwwwwwwwwwwwwwwwwwwwrdW',
    'W...          .W....d...r...d.........rW',
    'W...          .W.d....................rW',
    'W..................r..............dd...W',
    'W.P..r.........W.................d...E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
