import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** G — Butterfly Vault. Eight cells, eight tenants, one boulder each. */
export const caveG: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveG',
  letter: 'G',
  name: 'Butterfly Vault',
  paletteId: 'verdant',
  hint: 'Butterflies die rich. Drop something heavy on one.',
  diamondsRequired: 22,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 145,
  tickHz: 7.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W......................................W',
    'W....r......r......r......r............W',
    'W..w...w..w...w..w...w..w...w..........W',
    'W..w   w..w   w..w   w..w   w..........W',
    'W..w b w..w b w..w b w..w b w..........W',
    'W..wwwww..wwwww..wwwww..wwwww..........W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W......................................W',
    'W........r......r......r......r........W',
    'W......w...w..w...w..w...w..w...w......W',
    'W......w   w..w   w..w   w..w   w......W',
    'W......w b w..w b w..w b w..w b w......W',
    'W......wwwww..wwwww..wwwww..wwwww......W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
