import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** R — Blast Passage. Two firefly charges breach two distant vaults. */
export const caveR: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveR',
  letter: 'R',
  name: 'Blast Passage',
  paletteId: 'rust',
  hint: 'The treasure is behind brick; the two trapped sparks are your charges.',
  objective: 'Breach both distant firefly vaults without entering either blast zone.',
  mechanics: ['gravity', 'fireflies'],
  difficulty: 4,
  diamondsRequired: 20,
  diamondValue: 15,
  extraDiamondValue: 30,
  timeLimit: 65,
  tickHz: 9,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W.........rwwwwwwww....................W',
    'W..........w.d.d.dw....d...............W',
    'W........wfw.d.d.dw....................W',
    'W........www.d.d.dw....................W',
    'W..........wwwwwwww....................W',
    'W......................................W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWW',
    'W......................................W',
    'W...........................rwwwwwwww..W',
    'W............................w.d.d.dw..W',
    'W..........................wFw.d.d.dw..W',
    'W.....d....................www.d.d.dw..W',
    'W............................wwwwwwww..W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
