import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** L — Bloom Chase. A closing approach leads to a live containment station. */
export const caveL: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveL',
  letter: 'L',
  name: 'Bloom Chase',
  paletteId: 'amethyst',
  hint: 'Run the closing gallery, push the vent plug, then return to the spark door.',
  objective: 'Beat the expanding wall and contain the bloom before opening its roof.',
  mechanics: ['digging', 'expanding-wall', 'amoeba', 'boulder-pushing', 'fireflies'],
  difficulty: 3,
  diamondsRequired: 10,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 85,
  tickHz: 8.25,
  amoebaSlowGrowthTicks: 300,
  amoebaSlowGrowthChance: 0.04,
  amoebaGrowthChance: 0.35,
  amoebaMaxSize: 18,
  pushChance: 1,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWHP......d.........d.........d....WWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.EWWWW',
    'WWWW....d........d.........d...........W',
    'WWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWr.W',
    'WWWW.WWWWWWWWWWWWWWWWWWWWWWwwwwwwwwww..W',
    'WWWW.WWWWWWWWWWWWWWWWWWWWWW....a...awfwW',
    'WWWW.WWWWWWWWWWWWWWWWWWWWWW.wwwwdwwwwwwW',
    'WWWW......d........d.....r  WWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWW WWWWWWWWWWWWW',
    'WWWWWW.................... ...........WW',
    'WWWWWW................................WW',
    'WWWWWW................................WW',
    'WWWWWW................................WW',
    'WWWWWW................................WW',
    'WWWWWW................................WW',
    'WWWWWW................................WW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
