import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** F — Double Fuse. A terraced outer keep contains the second demolition lock. */
export const caveF: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveF',
  letter: 'F',
  name: 'Double Fuse',
  paletteId: 'ember',
  hint: 'Breach the keep, cross its upper ledge, then reach the inner fuse from the side.',
  objective: 'Open the outer keep before descending to the second lock and its treasury.',
  mechanics: ['gravity', 'fireflies'],
  difficulty: 2,
  diamondsRequired: 14,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 95,
  tickHz: 7.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W..........WWWWWWWWWWWWWWWWWWWWWWWW....W',
    'W...d......W.....d.......W...d....W....W',
    'W..........W.........d...W........W....W',
    'W.........rW.............W......d.W....W',
    'W..........w.............W........W....W',
    'W........wfw....d........W........W....W',
    'W.........ww.............W..d.....W....W',
    'W..........WWWWWWWWWWWW..W........W....W',
    'W..........W............rW........W....W',
    'W..........W.............w.....d..W....W',
    'W..........W......d....wfw........W....W',
    'W..........W............ww........W....W',
    'W..........W.............W...d....W....W',
    'W.......d..W...d.........W........W....W',
    'W..........W..........d..W.......dW....W',
    'W..........WWWWWWWWWWWWWWWWWWWWWWWW....W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
