import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** G — Butterfly Vault. Butterflies die rich. Drop something heavy on one. */
export const caveG: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveG',
  letter: 'G',
  name: 'Butterfly Vault',
  paletteId: 'verdant',
  hint: 'Butterflies die rich. Drop something heavy on one.',
  diamondsRequired: 16,
  diamondValue: 15,
  extraDiamondValue: 35,
  timeLimit: 155,
  tickHz: 7.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W..d......d.........d.........d.....d..W',
    'W.P.....r.......rr......r.......r......W',
    'W.......r.......r.......r......rr......W',
    'W....d.. ....... ....... ....... .d....W',
    'W...d... ....... ....d.. ....... ......W',
    'W....... ....... ....d.. ...d... ......W',
    'W.r..www www.www www.www www.www www...W',
    'W....w     w.w     w.w     w.w     w...W',
    'Wr...w     w.w     wdw     w.w     w..dW',
    'W....w     w.w     w.w     w.w     w...W',
    'W....w  b  wrw  b  w.w  b  w.w  b  w...W',
    'W....w     w.w     w.w     w.w     w...W',
    'W....w     w.w     w.w     w.w     w...W',
    'W....wwwwwww.wwwwwww.wwwwwww.wwwwwww...W',
    'W....d......d............d.......r.....W',
    'W..d.......................r...........W',
    'W.........r.......r..d....d............W',
    'W.......d.....................d........W',
    'W..................r.....d.............W',
    'W......................r.............E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
