import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** T — One Way Out. Twenty caves. This is the one that counts. */
export const caveT: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveT',
  letter: 'T',
  name: 'One Way Out',
  paletteId: 'obsidian',
  hint: 'Twenty caves. This is the one that counts.',
  diamondsRequired: 30,
  diamondValue: 20,
  extraDiamondValue: 50,
  timeLimit: 165,
  tickHz: 9,
  amoebaSlowGrowthTicks: 50,
  amoebaGrowthChance: 0.26,
  amoebaMaxSize: 80,
  magicWallTicks: 130,
  slimePermeability: 0.2,
  pushChance: 0.2,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W..........d.d....d.wwwwwwwwwwwwwwwww..W',
    'W..    r      r  ...w     d d       w..W',
    'W..r     rr      ...w               ...W',
    'W..   r    r  rr ...w     d a       w.dW',
    'W..r   r   rr   r...w               w..W',
    'W..  rrr  d r    ...w        d      w..W',
    'W.. r     r r r  .dd.          d    w.dW',
    'W...d...............wwwwwwwwwwwwwwwww..W',
    'W..MMMMMMMMMMMMMM....rd.r..r..r..r.....W',
    'W..              ..dSSSSSSSSSSSSSSSSS.dW',
    'W..              ....               d..W',
    'W..              ....               ...W',
    'W.WWWWWWWWWWWWWWWW...  b    B    b  ...W',
    'W...d.....d...d...d..               ...W',
    'W....d...............   d   d       ..dW',
    'W....d.........d............dd....d....W',
    'W.WWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWW.W',
    'W.    f           f           f       .W',
    'W.d.                                ...W',
    'W.P.......d.............d............E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
