import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** T — One Way Out. Seam, wings and colony, in that order, with the clock running. */
export const caveT: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveT',
  letter: 'T',
  name: 'One Way Out',
  paletteId: 'obsidian',
  hint: 'Everything this cave taught you, in one run, in the right order.',
  diamondsRequired: 32,
  diamondValue: 20,
  extraDiamondValue: 40,
  timeLimit: 165,
  tickHz: 9,
  magicWallTicks: 150,
  slimePermeability: 0.2,
  amoebaGrowthChance: 0.26,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..W',
    'W......................................W',
    'W..MMMMMMMMMMMM......MMMMMMMMMMMMMMMM..W',
    'W..            ......                ..W',
    'W..WWWWWWWWWWWWWWWWWWSSSSSSWWWWWWWWWW..W',
    'W..W                                W..W',
    'W..W b      b      f      b      b  W..W',
    'W..W                                W..W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W.........wwwwwwwwwwwwwwwwwwww.........W',
    'W.........w    aa    aa      w.........W',
    'W.........wwwwwwwwwrwwwwwwwwww.........W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
