import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** E — Firefly Warren. Guarded cells, each with one door and one tenant. */
export const caveE: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveE',
  letter: 'E',
  name: 'Firefly Warren',
  paletteId: 'ember',
  hint: 'Fireflies hug the wall on their left. Learn the loop.',
  diamondsRequired: 18,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 135,
  tickHz: 7.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d.......d.......d.......d.......d..W',
    'W......................................W',
    'W..wwwwww...wwwwww...wwwwww...wwwwww...W',
    'W..w f  w...w  f w...w f  w...w  f w...W',
    'W..w dd w...w dd w...w dd w...w dd w...W',
    'W..w    w...w    w...w    w...w    w...W',
    'W..www.ww...www.ww...www.ww...www.ww...W',
    'W......................................W',
    'W.....d...d...d...d...d...d...d...d....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWW....WWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W..wwwwww...wwwwww...wwwwww...wwwwww...W',
    'W..w  f w...w f  w...w  f w...w f  w...W',
    'W..w dd w...w dd w...w dd w...w dd w...W',
    'W..w    w...w    w...w    w...w    w...W',
    'W..www.ww...www.ww...www.ww...www.ww...W',
    'W......................................W',
    'W.....d...d...d...d...d...d...d...d..E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
