import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** H — Magic Seam. A hopper of scree resting on a seam that pays in diamond. */
export const caveH: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveH',
  letter: 'H',
  name: 'Magic Seam',
  paletteId: 'verdant',
  hint: 'The seam turns stone to diamond -- but only while it burns.',
  diamondsRequired: 24,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 140,
  tickHz: 7.5,
  magicWallTicks: 190,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d.......d.......d.......d.......d..W',
    'W......................................W',
    'W.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.W',
    'W......................................W',
    'W.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.W',
    'W.                                    .W',
    'W.                                    .W',
    'W.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..rrrrrrrrrrrrrr......rrrrrrrrrrrrrr..W',
    'W......................................W',
    'W..MMMMMMMMMMMMMM......MMMMMMMMMMMMMM..W',
    'W..            ......            ......W',
    'W..            ......            ......W',
    'W..WWWWWWWWWWWW......WWWWWWWWWWWW......W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
