import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** S — Cascade. Seventy-two rocks, a membrane, a seam, and a basin. */
export const caveS: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveS',
  letter: 'S',
  name: 'Cascade',
  paletteId: 'obsidian',
  hint: 'Open the floor and stand well clear. The seam does the rest.',
  diamondsRequired: 30,
  diamondValue: 15,
  extraDiamondValue: 30,
  timeLimit: 140,
  tickHz: 9,
  magicWallTicks: 150,
  slimePermeability: 0.22,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.W',
    'W.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.W',
    'W......................................W',
    'W.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.W',
    'W.                                    .W',
    'W.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.W',
    'W.                                    .W',
    'W.                                    .W',
    'W.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..rr..rr..rr..rr..rr..rr..rr..rr..rr..W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWW....WWWWWWWWWWWWWWWW..W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
