import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** P — Alloy and Wings. Eight conversions and one rich blast make the quota. */
export const caveP: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveP',
  letter: 'P',
  name: 'Alloy and Wings',
  paletteId: 'obsidian',
  hint: 'Run every furnace, then use the last suspended rock on the nest.',
  objective: 'Combine eight magic-wall conversions with one controlled rich blast.',
  mechanics: ['gravity', 'magic-wall', 'butterflies'],
  difficulty: 4,
  diamondsRequired: 16,
  diamondValue: 15,
  extraDiamondValue: 30,
  timeLimit: 70,
  tickHz: 8.5,
  magicWallTicks: 320,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W......................................W',
    'W....r...r...r...r...r...r...r...r.....W',
    'W......................................W',
    'W....M...M...M...M...M...M...M...M.....W',
    'W.... ... ... ... ... ... ... ... .....W',
    'W.... ... ... ... ... ... ... ... .....W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWW',
    'W......................................W',
    'W......................................W',
    'W..................r...................W',
    'W...d...............w..................W',
    'W.................wbw..................W',
    'W.................www..........d.......W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
