import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** O — Amoeba Bloom. Let it grow too long and the whole cave turns to stone. */
export const caveO: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveO',
  letter: 'O',
  name: 'Amoeba Bloom',
  paletteId: 'sulphur',
  hint: 'Let it grow too long and the whole cave turns to stone.',
  diamondsRequired: 24,
  diamondValue: 14,
  extraDiamondValue: 35,
  timeLimit: 155,
  tickHz: 8,
  amoebaSlowGrowthTicks: 60,
  amoebaGrowthChance: 0.24,
  amoebaMaxSize: 90,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W....r.d................rdd............W',
    'W.P..................................d.W',
    'W...r........r.............r....dd.....W',
    'W..d..................d................W',
    'W....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww....W',
    'Wd...w  r   r   r   r   r   r   r .....W',
    'W..d.w                            w....W',
    'W....w                            w....W',
    'W....w                            w...rW',
    'W....w      a                     w....W',
    'W....w                     a      w....W',
    'W....w                            w....W',
    'W....w                            w....W',
    'W....w                            w....W',
    'W.r...                            w....W',
    'W....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww....W',
    'W......r.......................d.......W',
    'W.................r............r....d..W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
