import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** J — Green Tide. Wall the amoeba in and it hardens into diamond. */
export const caveJ: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveJ',
  letter: 'J',
  name: 'Green Tide',
  paletteId: 'amethyst',
  hint: 'Wall the amoeba in and it hardens into diamond.',
  diamondsRequired: 20,
  diamondValue: 12,
  extraDiamondValue: 30,
  timeLimit: 160,
  tickHz: 7.5,
  amoebaSlowGrowthTicks: 120,
  amoebaGrowthChance: 0.16,
  amoebaMaxSize: 130,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W....d.........d......d......dd......drW',
    'W.P...........................r........W',
    'W................d..................r..W',
    'W.....d.....................r..........W',
    'W.........d.........d.........d........W',
    'W..........r...........................W',
    'W.......r.....wwwwwwwwwwww.............W',
    'W........d....w...r......w.............W',
    'W.d.....r.....w.      ...w.............W',
    'W.............w.  a   ...w.............W',
    'W.......r....r..   a  ...........r...rdW',
    'W......r......w.      ...w.d...........W',
    'W..r..........w..........w.....r.......W',
    'W.......d.....w......rr..w.............W',
    'W.............wwwwwwwwwwww......r......W',
    'W......................................W',
    'W....................................r.W',
    'W.....d.........r...r.................dW',
    'W..d....d.......d...........d..........W',
    'W...r.......d............d...........E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
