import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** M — Slime Pits. Scree resting on membrane, and a basin waiting underneath. */
export const caveM: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveM',
  letter: 'M',
  name: 'Slime Pits',
  paletteId: 'sulphur',
  hint: 'Slime lets stone through. Eventually. Never predictably.',
  diamondsRequired: 26,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 140,
  tickHz: 8,
  slimePermeability: 0.18,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..rrdrrrdrrrdrrrdrrrdrrrdrrrdrrrdrr...W',
    'W..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....W',
    'W..                                ....W',
    'W..                                ....W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW....W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W....rrdrrrdrrrdrrrdrrrdrrrdrrrdrrrd...W',
    'W....SSSSSSSSSSSSSSSSSSSSSSSSSSSS......W',
    'W....                            ......W',
    'W....                            ......W',
    'W....WWWWWWWWWWWWWWWWWWWWWWWWWWWW......W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
