import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** J — Seed Crystal. Plug a live vent, then blast open the mature mould. */
export const caveJ: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveJ',
  letter: 'J',
  name: 'Seed Crystal',
  paletteId: 'amethyst',
  hint: 'Push the rock left twice. When the bloom flashes, open the spark door.',
  objective: 'Contain the live amoeba, then breach its mould and harvest the crystals.',
  mechanics: ['amoeba', 'boulder-pushing', 'fireflies'],
  difficulty: 3,
  diamondsRequired: 18,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 70,
  tickHz: 8,
  amoebaSlowGrowthTicks: 220,
  amoebaSlowGrowthChance: 0.12,
  amoebaGrowthChance: 0.4,
  amoebaMaxSize: 32,
  pushChance: 1,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W...........W.................r........W',
    'W....wwwwwwwdwwwwwwwwwwwwwwwww.........W',
    'W...W.....a........a.........wfw.......W',
    'W...W.Wwwwwwwwwwwwwwwwwwwwwwwwww.......W',
    'W...W.W................................W',
    'W...W.WWW..............................W',
    'W...W  rPE.............................W',
    'W..... WW..............................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
