import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** I — Relay Kilns. Three short banks relay a charge around a broken central spine. */
export const caveI: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveI',
  letter: 'I',
  name: 'Relay Kilns',
  paletteId: 'verdant',
  hint: 'Work the three terraces around the spine before the shared charge fades.',
  objective: 'Relay stone through three separated furnace banks and gather their output.',
  mechanics: ['gravity', 'magic-wall'],
  difficulty: 2,
  diamondsRequired: 13,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 80,
  tickHz: 7.75,
  magicWallTicks: 340,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P...............W....................W',
    'W.................W....................W',
    'W...r..r..r..r....W....................W',
    'W.................W....................W',
    'W...M..M..M..M....W....................W',
    'W... .. .. .. ....W....................W',
    'W... .. .. .. ....W....................W',
    'W.................W....r..r..r..r......W',
    'W.................W....................W',
    'WWWWWWWWWWWWWWWW..W....M..M..M..M......W',
    'W...................... .. .. .. ......W',
    'W...................... .. .. .. ......W',
    'W......................................W',
    'W....r..r..r..r...W....................W',
    'W.................WWWWWWWWWWWWWWWWW.WWWW',
    'W....M..M..M..M...W....................W',
    'W.... .. .. .. ...W....................W',
    'W..d. .. .. .. ...W....................W',
    'W.................W....................W',
    'W.................W..................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
