import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** Q — Three Charges. Three reinforced nests each yield exactly six safe diamonds. */
export const caveQ: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveQ',
  letter: 'Q',
  name: 'Three Charges',
  paletteId: 'obsidian',
  hint: 'The steel cheeks shape each blast. Clear all three supports.',
  objective: 'Detonate all three reinforced nests for their measured diamond yield.',
  mechanics: ['gravity', 'butterflies'],
  difficulty: 4,
  diamondsRequired: 20,
  diamondValue: 15,
  extraDiamondValue: 30,
  timeLimit: 65,
  tickHz: 8.75,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W...d..................................W',
    'W......................................W',
    'W.......r...........r...........r......W',
    'W......................................W',
    'W......WbW.........WbW.........WbW.....W',
    'W......wWw.........wWw.........wWw.....W',
    'W......................................W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWW',
    'W..................................d...W',
    'W......................................W',
    'W......................................W',
    'W.......wwwww..........................W',
    'W.....................wwwwww...........W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
