import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** E — Spark Lock. A trapped firefly is the key to a brick vault. */
export const caveE: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveE',
  letter: 'E',
  name: 'Spark Lock',
  paletteId: 'ember',
  hint: 'Drop the marked boulder; the blast opens what your pick cannot.',
  objective: 'Crush the trapped firefly to breach the first sealed diamond vault.',
  mechanics: ['gravity', 'fireflies'],
  difficulty: 2,
  diamondsRequired: 10,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 60,
  tickHz: 7.25,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W....d.....rwwwwwwwwww.................W',
    'W...........w.d.d.d..w........d........W',
    'W.........wfw.d.d.d..w.................W',
    'W.........www.d.d.d..w.................W',
    'W...........wwwwwwwwww.................W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'W......................................W',
    'W......................................W',
    'W....wwww....................wwwww.....W',
    'W......d...............................W',
    'W..............wwwwww..................W',
    'W.........................d............W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
