import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** F — Double Fuse. Two demolition locks must be sprung in sequence. */
export const caveF: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveF',
  letter: 'F',
  name: 'Double Fuse',
  paletteId: 'ember',
  hint: 'A falling boulder clears brick. Keep clear of both blast doors.',
  objective: 'Trigger both demolition locks and collect from the opened rooms.',
  mechanics: ['gravity', 'fireflies'],
  difficulty: 2,
  diamondsRequired: 14,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 95,
  tickHz: 7.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W........rwwwwwww......................W',
    'W.........w.d.d.w......................W',
    'W.......wFw.d.d.w.........d............W',
    'W.......www.d.d.w......................W',
    'W.........wwwwwww......................W',
    'W...d..................................W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWW',
    'W......................................W',
    'W......................................W',
    'W............................rwwwwwww..W',
    'W......d......................w.d.d.w..W',
    'W...........................wfw.d.d.w..W',
    'W...........................www.d.d.w..W',
    'W.............................wwwwwww..W',
    'W.................d....................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
