import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** J — Green Tide. A colony behind brick, and a door you choose when to open. */
export const caveJ: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveJ',
  letter: 'J',
  name: 'Green Tide',
  paletteId: 'amethyst',
  hint: 'Wall the amoeba in and it hardens into diamond.',
  diamondsRequired: 22,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 150,
  tickHz: 7.5,
  amoebaGrowthChance: 0.16,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W......wwwwwwwwwwww....................W',
    'W......w..........w....................W',
    'W......w....aa....w....................W',
    'W......w..........w....................W',
    'W......wwwwwwrwwwww....................W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W..rr..rr..rr..rr..rr..rr..rr..rr..rr..W',
    'W......................................W',
    'W......................................W',
    'W..WWWWWWWWWWWWWW....WWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
