import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** N — Double Trouble. Two sealed runs, two species, scree resting on both lids. */
export const caveN: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveN',
  letter: 'N',
  name: 'Double Trouble',
  paletteId: 'sulphur',
  hint: 'One kind turns left, the other turns right. Both turn on you.',
  diamondsRequired: 24,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 145,
  tickHz: 8,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W..rr..rr..rr..rr..rr..rr..rr..rr..rr..W',
    'W......................................W',
    'W.     f          b          f        .W',
    'W.                                    .W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W..rr..rr..rr..rr..rr..rr..rr..rr..rr..W',
    'W......................................W',
    'W.    b          F          b         .W',
    'W.                                    .W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
