import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** C — Side Pocket. The first boulder gate teaches a safe horizontal push. */
export const caveC: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveC',
  letter: 'C',
  name: 'Side Pocket',
  paletteId: 'rime',
  hint: 'Push the plug over the drop, then follow the galleries to the lift.',
  objective: 'Push the first rock into its shaft to open the one-way gallery.',
  mechanics: ['digging', 'gravity', 'boulder-pushing'],
  difficulty: 1,
  diamondsRequired: 11,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 70,
  tickHz: 7,
  pushChance: 1,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WW.P.....r .d..d...d.....d.....d.....WWW',
    'WWWWWWWWWW WWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWdWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWdWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWW.......d........d........d......WWW',
    'WWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWW...........d....................EWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
