import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** O — Twin Blooms. Offset basins join through a chimney above a deep live vent. */
export const caveO: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveO',
  letter: 'O',
  name: 'Twin Blooms',
  paletteId: 'sulphur',
  hint: 'Plug the deep vent. Breach the lower basin, then climb the crystal chimney.',
  objective: 'Contain two offset blooms, blast the lower door, and harvest upward through the elbow.',
  mechanics: ['amoeba', 'boulder-pushing', 'fireflies'],
  difficulty: 4,
  diamondsRequired: 28,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 80,
  tickHz: 8.5,
  amoebaSlowGrowthTicks: 300,
  amoebaSlowGrowthChance: 0.08,
  amoebaGrowthChance: 0.35,
  amoebaMaxSize: 40,
  pushChance: 1,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W......................................W',
    'W...........W..........................W',
    'W........WWWdWWWW......................W',
    'W.......W..a.....W.....................W',
    'W.......W.WWWWWW.W.....................W',
    'W.......W.W....W.W.....................W',
    'W.......W.W....W.W...........r.........W',
    'W.......W.W....W.WWWWWWWWWWWw..........W',
    'W.......W.W....W.......a....wfw........W',
    'W.......W.W.....WWWWWWWWWWWWwww........W',
    'W.......W.W............................W',
    'W.......W.WWW..........................W',
    'W.......W  rPE.........................W',
    'W........W WW..........................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
