import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** A — Buried River. A broad mineral field broken by long, staggered rock shelves. */
export const caveA: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveA',
  letter: 'A',
  name: 'Buried River',
  paletteId: 'glacier',
  hint: 'Pick twelve gems from the field. Dig beside loaded rocks, not underneath them.',
  objective: 'Cross the mineral-filled strata, collecting safe gems and reading the rockfalls.',
  mechanics: ['digging', 'gravity'],
  difficulty: 1,
  diamondsRequired: 12,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 75,
  tickHz: 6.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W......rdr..r........rr......  .... ...W',
    'W..P .....r. d......rrr..r..d......d...W',
    'W.. ..rr..d.....rr.d.....r ..rr.r .... W',
    'W.....r.r....r .r..........d....r....r.W',
    'W....dd.rr....r........rr.d..r.r.. ...rW',
    'W.wwwwwwwwwwwwwwww..wwwwwwwww.r.....r..W',
    'W....r...r.r.. . .......d. ............W',
    'W..rr.r...d......r.....d.rr...... .....W',
    'W.r......r ....d....r.r.......... r....W',
    'W.r.....d.r..r..r........r..rd.........W',
    'W.rr.r....... .... .. .d...r...r..  ...W',
    'W.d...... .wwwwwwwwwwwww..wwwwwwwwwwww.W',
    'W... .r.........rr..d...r....d..r..d...W',
    'W.......d......rdr ......d......r....r.W',
    'W.......r......rr......................W',
    'Wr.. ....r......r.r.............r......W',
    'W..wwwwww..wwwwwwwwwwwwdr......rr......W',
    'W............rrd.r.. .drd.d............W',
    'W...... ... ....r......d...r........E..W',
    'Wd.dd..d.r...rd...r...r.r......  ......W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
