import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** B — Rockfall. Cascading scree and alcoves you can only enter side-on. */
export const caveB: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveB',
  letter: 'B',
  name: 'Rockfall',
  paletteId: 'glacier',
  hint: 'Boulders roll off round edges. Never stand below one.',
  diamondsRequired: 16,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 135,
  tickHz: 7,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W.......r.........r.........r..........W',
    'W......rrr.......rrr.......rrr.........W',
    'W.....rrrrr.....rrrrr.....rrrrr........W',
    'W....rrrrrrr...rrrrrrr...rrrrrrr.......W',
    'W.....d...d.....d...d.....d...d........W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW...W',
    'W......................................W',
    'W.d..r..d..r..d..r..d..r..d..r..d..r...W',
    'W......................................W',
    'W...rrrr.....rrrr.....rrrr.....rrrr....W',
    'W...d..d.....d..d.....d..d.....d..d....W',
    'W......................................W',
    'W......................................W',
    'W..WWWWWWWWWWWW......WWWWWWWWWWWWWW....W',
    'W......................................W',
    'W....d....d....d....d....d....d....d...W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
