import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** K — Closing Shift. A wall grows into every cell the miner leaves behind. */
export const caveK: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveK',
  letter: 'K',
  name: 'Closing Shift',
  paletteId: 'rust',
  hint: 'The wall follows through empty ground. Keep moving; there is no return.',
  objective: 'Stay ahead of the expanding wall through the full one-way route.',
  mechanics: ['digging', 'expanding-wall'],
  difficulty: 3,
  diamondsRequired: 17,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 65,
  tickHz: 8,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWXP....d.......d........d........d..WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWW.......d.........d........d.......WWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWW....d........d.........d.......d..WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWW......d.........d.........d.......WWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWW.....d.........d.........d........EWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
