import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** K — Expanding Ruin. Galleries that build themselves shut behind you. */
export const caveK: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveK',
  letter: 'K',
  name: 'Expanding Ruin',
  paletteId: 'rust',
  hint: 'These walls are still being built. Do not be inside them.',
  diamondsRequired: 20,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 135,
  tickHz: 8,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W..      d      H       d            ..W',
    'W..WWWWWWWWWWWW......WWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W..      d        X        d         ..W',
    'W..                                  ..W',
    'W..WWWWWWWWWWWWWWWW....WWWWWWWWWWWWWW..W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W.......V.............V................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
