import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** F — Crush Depth. Sealed runs full of fireflies, with scree resting overhead. */
export const caveF: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveF',
  letter: 'F',
  name: 'Crush Depth',
  paletteId: 'ember',
  hint: 'A falling boulder settles an argument with a firefly.',
  diamondsRequired: 20,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 130,
  tickHz: 8,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W.rr..rr..rr..rr..rr..rr..rr..rr..rr...W',
    'W......................................W',
    'W.   f                          f     .W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W.rr..rr..rr..rr..rr..rr..rr..rr..rr...W',
    'W......................................W',
    'W.     f                    f         .W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
