import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** D — Switchbacks. Three push-and-drop gates link a winding descent. */
export const caveD: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveD',
  letter: 'D',
  name: 'Switchbacks',
  paletteId: 'ember',
  hint: 'Read each turn: the empty shaft beyond the plug is the safe side.',
  objective: 'Clear three alternating push gates while descending the switchbacks.',
  mechanics: ['digging', 'gravity', 'boulder-pushing'],
  difficulty: 1,
  diamondsRequired: 12,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 85,
  tickHz: 7.25,
  pushChance: 1,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WW.P.....r .dddd.....................WWW',
    'WWWWWWWWWW WWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWW WWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWW WWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWW....................dddd. r.......WWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWW WWWWWWWWWWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWW WWWWWWWWWWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWW WWWWWWWWWWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWW......r .dddd.....................WWW',
    'WWWWWWWWWW WWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWW WWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWW WWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWW',
    'WWW..................................WWW',
    'WWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWW..................................EWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
