import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** A — First Descent. Dig for diamonds. Mind what falls. */
export const caveA: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveA',
  letter: 'A',
  name: 'First Descent',
  paletteId: 'glacier',
  hint: 'Dig for diamonds. Mind what falls.',
  diamondsRequired: 14,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 140,
  tickHz: 7,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W....rrrrr......rrrrr......rrrrr.......W',
    'W....d...d......d...d......d...d.......W',
    'W......................................W',
    'W...WWWWWWWWWWWW....WWWWWWWWWWWW.......W',
    'W......................................W',
    'W..d....r....d....r....d....r....d.....W',
    'W......................................W',
    'W.....rrrrrrrr........rrrrrrrr.........W',
    'W.....d.dd.d..........d.dd.d...........W',
    'W......................................W',
    'W........WWWWWWWWWWWWWWWWWW............W',
    'W......................................W',
    'W...d.r...d.r...d.r...d.r...d.r...d....W',
    'W......................................W',
    'W......rr......rr......rr......rr......W',
    'W......dd......dd......dd......dd......W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
