import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** R — Blast Passage. A dogleg mining adit has an entrance charge and a shaft charge. */
export const caveR: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveR',
  letter: 'R',
  name: 'Blast Passage',
  paletteId: 'rust',
  hint: 'Blast into the adit. At the far bend, sidestep the shaft charge before descending.',
  objective: 'Open the winding passage, clear its vertical fuse, and mine the return arm.',
  mechanics: ['gravity', 'fireflies'],
  difficulty: 4,
  diamondsRequired: 24,
  diamondValue: 15,
  extraDiamondValue: 30,
  timeLimit: 65,
  tickHz: 9,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W......................................W',
    'W.....r................................W',
    'W......wWWWWWWWWWWWWWWWWWWWWWW.........W',
    'W....wfw.d.d.d.d.d.d.d.d.d.d..W........W',
    'W.....wwWWWWWWWWWWWWWWWWWWWW..W........W',
    'W..........................Wr.W........W',
    'W..........................W..W........W',
    'W.............WWWWWWWW.....wfW.........W',
    'W............Wdddd.d.dW....WwW.........W',
    'W............W.WWWWWWW.....W.W.........W',
    'W............WdW...........W.W.........W',
    'W............W.WWWWWWWWWWWWW.W.........W',
    'W............W.d.d.d.d.d.d.d.W.........W',
    'W.............WWWWWWWWWWWWWWW..........W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
