import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** O — Amoeba Bloom. One colony, one shelf of scree, and a decision. */
export const caveO: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveO',
  letter: 'O',
  name: 'Amoeba Bloom',
  paletteId: 'sulphur',
  hint: 'Let it grow too long and the whole cave turns to stone.',
  diamondsRequired: 28,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 150,
  tickHz: 8,
  amoebaGrowthChance: 0.24,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..W',
    'W......................................W',
    'W..................aa..................W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..rr..rr..rr..rr..rr..rr..rr..rr..rr..W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWW....WWWWWWWWWWWWWWWW..W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
