import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** P — The Crucible. A wide seam, a short fuse, and wings below it. */
export const caveP: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveP',
  letter: 'P',
  name: 'The Crucible',
  paletteId: 'obsidian',
  hint: 'The seam only runs once. Have every rock ready before you wake it.',
  diamondsRequired: 28,
  diamondValue: 15,
  extraDiamondValue: 30,
  timeLimit: 145,
  tickHz: 8.5,
  magicWallTicks: 160,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..W',
    'W......................................W',
    'W..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..W',
    'W..                                  ..W',
    'W..                                  ..W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W..                                  ..W',
    'W..   b      b      b      b      b  ..W',
    'W..                                  ..W',
    'W..rr..rr..rr..rr..rr..rr..rr..rr..rr..W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
