import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** T — Foundry Run. Every production mechanic feeds one final quota. */
export const caveT: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveT',
  letter: 'T',
  name: 'Foundry Run',
  paletteId: 'obsidian',
  hint: 'Run the cascade, seal the live vent, then open both blast-fed vaults.',
  objective: 'Combine every production system, including a player-contained crystal bloom.',
  mechanics: [
    'gravity',
    'slime',
    'magic-wall',
    'fireflies',
    'butterflies',
    'amoeba',
    'boulder-pushing',
  ],
  difficulty: 5,
  diamondsRequired: 33,
  diamondValue: 20,
  extraDiamondValue: 40,
  timeLimit: 130,
  tickHz: 9.25,
  magicWallTicks: 300,
  slimePermeability: 0.6,
  amoebaSlowGrowthTicks: 500,
  amoebaSlowGrowthChance: 0.005,
  amoebaGrowthChance: 0.35,
  amoebaMaxSize: 30,
  pushChance: 1,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W..................................r...W',
    'W...r....r....r....r....r....r.........W',
    'W......................................W',
    'W...S....S....S....S....S....S.........W',
    'W... .... .... .... .... .... ....wfw..W',
    'W...M....M....M....M....M....M...wwwww.W',
    'W... .... .... .... .... .... ...wdddw.W',
    'W... .... .... .... .... .... ...wdddw.W',
    'W...............................rwwwww.W',
    'WW.EWWWWWWWWWWWWWWWWWWWWWWWWWW.....WWWWW',
    'WW.WWWWWWWWWWwwdwwwwwwwwwwwwwwwW W..WWWW',
    'WW.WWWWWWWWWW.....a........a...wbW.WWWWW',
    'WW.WWWWWWWWWW.wwwwwwwwwwwwwwwwwWWW.WWWWW',
    'WW.........r  WWWWWWWWWWWWWWWWWWW..WWWWW',
    'WWWWWWWWWWWW..........................WW',
    'WWWWWWWWWWWW..........................WW',
    'WWWWWWWWWWWW..........................WW',
    'WWWWWWWWWWWW..........................WW',
    'WWWWWWWWWWWW..........................WW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
