import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** M — Membrane Drop. Four boulders must seep through slime into four nests. */
export const caveM: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveM',
  letter: 'M',
  name: 'Membrane Drop',
  paletteId: 'sulphur',
  hint: 'Release each boulder and let the membrane deliver it to the nest.',
  objective: 'Send all four stones through slime to cash in the butterfly nests.',
  mechanics: ['gravity', 'slime', 'butterflies'],
  difficulty: 3,
  diamondsRequired: 30,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 55,
  tickHz: 8.25,
  slimePermeability: 0.55,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'W......................................W',
    'W......r.......r.......r.......r.......W',
    'W......................................W',
    'W......S.......S.......S.......S.......W',
    'W...... ....... ....... ....... .......W',
    'W.....wbw.....wbw.....wbw.....wbw......W',
    'W.....www.....www.....www.....www......W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWW',
    'W......................................W',
    'W......................................W',
    'W...d..................................W',
    'W......................................W',
    'W...........................d..........W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
