import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** Q — Three Charges. Moving butterflies patrol three differently shaped demolition courts. */
export const caveQ: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveQ',
  letter: 'Q',
  name: 'Three Charges',
  paletteId: 'obsidian',
  hint: 'Watch each patrol before releasing its roof stones; keep out of the courts.',
  objective: 'Time exposed rockfalls over three moving butterfly patrols and harvest their blasts.',
  mechanics: ['gravity', 'butterflies'],
  difficulty: 4,
  diamondsRequired: 26,
  diamondValue: 15,
  extraDiamondValue: 30,
  timeLimit: 65,
  tickHz: 8.75,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P.........................r...r......W',
    'W...d..................................W',
    'W.......r..r..........wwwwww www www...W',
    'W.....................w     b      w...W',
    'W...wwww ww ww........w            w...W',
    'W...w   b    w........w            w...W',
    'W...w        w........wwwwwwwwwwwwww...W',
    'W...w        w.........................W',
    'W...w        w.........................W',
    'W...wwwwwwwwww.........................W',
    'W...................r.r................W',
    'W......................................W',
    'W...............wwww w ww..............W',
    'W...............w   b   w..............W',
    'W...............w       w..............W',
    'W...............w       w..........d...W',
    'W...............w       w..............W',
    'W...............w       w..............W',
    'W...............wwwwwwwww..............W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
