import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** H — Seven Furnaces. Feed each quiet seam before leaving the works. */
export const caveH: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveH',
  letter: 'H',
  name: 'Seven Furnaces',
  paletteId: 'verdant',
  hint: 'Cut each support from the side and collect below the glowing seam.',
  objective: 'Feed all seven stones through the magic wall and harvest their output.',
  mechanics: ['gravity', 'magic-wall'],
  difficulty: 2,
  diamondsRequired: 9,
  diamondValue: 10,
  extraDiamondValue: 25,
  timeLimit: 80,
  tickHz: 7.75,
  magicWallTicks: 260,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W......................................W',
    'WWWWWWWWWWWWWWWWW.WWWWWWWWWWWW.WWWWWWWWW',
    'W......................................W',
    'W....r....r....r....r....r....r....r...W',
    'W......................................W',
    'W....M....M....M....M....M....M....M...W',
    'W.... .... .... .... .... .... .... ...W',
    'W.... .... .... .... .... .... .... ...W',
    'W......................................W',
    'WWWWWWWWW.WWWWWWWWWWWW..WWWWWWWWWWWWWWWW',
    'W......................................W',
    'W......................................W',
    'W...d...WWWW......WWWWWW.....WWWW......W',
    'W......................................W',
    'W................................d.....W',
    'W......................................W',
    'W......................................W',
    'W......................................W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
