import { DEFAULT_TUNING } from '../../engine/simTypes';
import type { CaveSpec } from '../caveFormat';

/** R — Choke Point. Three patrolled runs, and only the edges to cross them. */
export const caveR: CaveSpec = {
  ...DEFAULT_TUNING,
  id: 'caveR',
  letter: 'R',
  name: 'Choke Point',
  paletteId: 'rust',
  hint: 'The only way down is along the walls. Count the patrol before you step.',
  diamondsRequired: 26,
  diamondValue: 15,
  extraDiamondValue: 30,
  timeLimit: 135,
  tickHz: 8.5,
  map: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'W.P....................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W.  f      f      f      f      f     .W',
    'W.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.W',
    'W......................................W',
    'W....d...d...d...d...d...d...d...d.....W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W.     F      F      F      F         .W',
    'W.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.W',
    'W......................................W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W......................................W',
    'W..WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..W',
    'W.  f      f      f      f      f     .W',
    'W.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.W',
    'W...d...d...d...d...d...d...d...d...d..W',
    'W....................................E.W',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
};
